OlauncherCF/OlauncherCF

fastlane/metadata/android/it-IT/full_description.txt, fastlane/metadata/android/it-IT/short_description.txt
Add Italian description. Thank @lichingyun 
closes #7
=> docs(translation): add italian translation

app/src/main/res/layout-land/fragment_settings.xml
Add language selector for landscape layout
=> fix(landscape): add language menu to landscape layout xml

app/src/main/res/values-es/strings.xml
Removed </resources> leftover tag
=> Update strings.xml to remove leftover tag

app/src/main/java/app/olaunchercf/MainActivity.kt, app/src/main/java/app/olaunchercf/data/Constants.kt, app/src/main/java/app/olaunchercf/helper/Utils.kt, app/src/main/res/layout-land/fragment_settings.xml, app/src/main/res/layout/fragment_settings.xml, app/src/main/res/values-cn/strings.xml, app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fr/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-se/strings.xml, app/src/main/res/values-tr-rTR/strings.xml, app/src/main/res/values/strings.xml
Removing translation to unsed strings
=> chore: remove unused strings

app/src/main/res/values-es/strings.xml
Some minor adjustments to Spanish language
=> Update Spanish translate

app/src/main/res/values-es/strings.xml
Updates some new strings to the Spanish language
=> Updated Spanish language

README.md
To follow the addition of the Greek to the next release
=> Adding Greek to Readme

app/src/main/res/values-de/strings.xml
Optimized german strings.
Hope  I made all right here on github cuz it is my first time to create a pull request ... ;-)
=> Optimize strings.xml

app/src/main/java/app/olaunchercf/MainViewModel.kt, app/src/main/java/app/olaunchercf/data/Prefs.kt, app/src/main/java/app/olaunchercf/ui/HomeFragment.kt, app/src/main/java/app/olaunchercf/ui/SettingsFragment.kt, app/src/main/res/layout/fragment_home.xml, app/src/main/res/values/strings.xml
=> feat: toggle date and time independently

app/src/main/res/values-fr/strings.xml, fastlane/metadata/android/fr-FR/full_description.txt, fastlane/metadata/android/fr-FR/short_description.txt
- Update french strings.xml file
- Creation of the file short_description.txt (in french)
- Creation of the full_description.txt file (in french)
=> Update french file

app/src/main/res/values-ko/strings.xml
Remove: show_date_time
Add: show_time, show_date
Update Dark, Light strings
=> Update korean strings

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/crash_report.md, .github/ISSUE_TEMPLATE/feature_request.md
A proposal to set up classic issue templates,
to avoid messy and unexplicit issues (like #83),
but also to make bug requests/feedback clearer, and easier to fill in for users.
Reject if useless, thanks
=> Proposal: implementation of Issue template

README.md, app/src/main/java/app/olaunchercf/data/Constants.kt, fastlane/metadata/android/en-US/full_description.txt, fastlane/metadata/android/fr-FR/full_description.txt
Linked to #81
- Added Indonesian to `constants.kt` file
- Added Indonesian to `readme.md` file
- Added Indonesian to `full_description.txt` file
=> Add Indonesian to settings

app/src/main/res/values-fr/strings.xml
Add lines (translated in french) to follow #97
=> Update french strings.xml

app/src/main/java/app/olaunchercf/data/Prefs.kt, app/src/main/java/app/olaunchercf/helper/Utils.kt, app/src/main/java/app/olaunchercf/ui/AppDrawerAdapter.kt, app/src/main/java/app/olaunchercf/ui/AppDrawerFragment.kt
=> fix: use packageName for applias identifier instead of appLabel

app/src/main/java/app/olaunchercf/ui/AppDrawerFragment.kt
=> fix: hidden apps string hardcoded

app/src/main/res/values-de/strings.xml, app/src/main/res/values-es/strings.xml, app/src/main/res/values-fa/strings.xml, app/src/main/res/values-gr/strings.xml, app/src/main/res/values-id/strings.xml, app/src/main/res/values-it/strings.xml, app/src/main/res/values-ko/strings.xml, app/src/main/res/values-pt-rPT/strings.xml, app/src/main/res/values-se/strings.xml, app/src/main/res/values-tr-rTR/strings.xml
- Optimization: removal of useless elements _(still present)_ like `translatable="false"` info, addition of line break _(to follow the reference file)_.
- Addition: Added missing strings _(compared to the reference file)_ to be translated in language files
=> Optimize language files

README.md, app/src/main/java/app/olaunchercf/data/Constants.kt, app/src/main/res/values-hr/strings.xml, fastlane/metadata/android/en-US/full_description.txt
=> Create Croatian (hr) translation file

app/src/main/java/app/olaunchercf/data/Prefs.kt, app/src/main/java/app/olaunchercf/ui/HomeFragment.kt, app/src/main/java/app/olaunchercf/ui/SettingsFragment.kt, app/src/main/java/app/olaunchercf/ui/compose/SettingsComposable.kt, app/src/main/res/values/strings.xml
Reorganizes settings
implements #125
=> Change settings

app/src/main/java/app/olaunchercf/MainViewModel.kt, app/src/main/java/app/olaunchercf/data/Prefs.kt, app/src/main/java/app/olaunchercf/ui/HomeFragment.kt
=> feat: implements #82

fastlane/metadata/android/hr-HR/full_description.txt, fastlane/metadata/android/hr-HR/short_description.txt
=> Create Croatian (hr) description files

app/src/main/res/values-es/strings.xml
Updated Spanish strings to match v1.1.0
=> Update Spanish strings.xml

app/src/main/java/app/olaunchercf/data/Prefs.kt, app/src/main/java/app/olaunchercf/ui/HomeFragment.kt, app/src/main/java/app/olaunchercf/ui/SettingsFragment.kt, app/src/main/res/values/strings.xml
This is related to https://github.com/jooooscha/Olauncher/issues/124 https://github.com/jooooscha/Olauncher/issues/143 https://github.com/jooooscha/Olauncher/issues/150
=> Optional extended clickable area for home apps

app/src/main/res/values-tr-rTR/strings.xml
I believe there are missing strings from recently added features, if they are added I'll also translate them.
=> Turkish strings update

app/src/main/res/values-de/strings.xml
Thanks to [R7010A](https://github.com/R7010A) in #168
=> feat(german): update german string

app/src/main/java/app/olaunchercf/ui/HomeFragment.kt
=> fix: home alignment when click area is exetended

app/src/main/java/app/olaunchercf/MainActivity.kt, app/src/main/java/app/olaunchercf/MainViewModel.kt, app/src/main/java/app/olaunchercf/data/Constants.kt, app/src/main/java/app/olaunchercf/data/Prefs.kt, app/src/main/java/app/olaunchercf/helper/Utils.kt, app/src/main/java/app/olaunchercf/ui/HomeFragment.kt, app/src/main/java/app/olaunchercf/ui/SettingsFragment.kt
closes #185
- could improve performance, as I improved the ViewModel situation
- General code improvement
- hopefully, I did not break anything
=> fix(homescreen): this fixes the homescreen alignment bug

app/src/main/java/app/olaunchercf/MainViewModel.kt, app/src/main/java/app/olaunchercf/data/Prefs.kt, app/src/main/java/app/olaunchercf/helper/Utils.kt, app/src/main/java/app/olaunchercf/ui/AppDrawerFragment.kt, app/src/main/java/app/olaunchercf/ui/HomeFragment.kt, app/src/main/java/app/olaunchercf/ui/SettingsFragment.kt, app/src/main/res/layout-land/fragment_app_drawer.xml, app/src/main/res/layout/fragment_app_drawer.xml, app/src/main/res/values/strings.xml
closes #184 
There was a check for if the app was installed, which failed for apps that are only on work profile
=> fix(homescreen): place apps that are only in work profile on home screen

app/src/main/res/values-de/strings.xml
=> fix: german translation

app/src/main/java/app/olaunchercf/MainViewModel.kt, app/src/main/java/app/olaunchercf/data/Constants.kt, app/src/main/java/app/olaunchercf/data/Prefs.kt, app/src/main/java/app/olaunchercf/style/Color.kt, app/src/main/java/app/olaunchercf/style/SettingsTheme.kt, app/src/main/java/app/olaunchercf/ui/AppDrawerAdapter.kt, app/src/main/java/app/olaunchercf/ui/AppDrawerFragment.kt, app/src/main/java/app/olaunchercf/ui/HomeFragment.kt, app/src/main/java/app/olaunchercf/ui/SettingsFragment.kt, app/src/main/java/app/olaunchercf/ui/compose/SettingsComposable.kt, app/src/main/res/layout-land/fragment_app_drawer.xml, app/src/main/res/layout/adapter_app_drawer.xml, app/src/main/res/layout/fragment_app_drawer.xml, app/src/main/res/values/strings.xml
=> Disable gestures

app/src/main/java/app/olaunchercf/data/Constants.kt, app/src/main/res/values-nl/strings.xml, fastlane/metadata/android/nl-NL/full_description.txt, fastlane/metadata/android/nl-NL/short_description.txt
This is the Dutch translation for the project. =)
=> Adding Dutch translation

README.md, app/src/main/java/app/olaunchercf/data/Constants.kt, app/src/main/res/values-lt/strings.xml
Add translations for Lithuanian
Signed-off-by: Ari Archer [ari.web.xyz@gmail.com](mailto:ari.web.xyz@gmail.com)
=> translations: Add translations for Lithuanian

app/src/main/java/app/olaunchercf/data/Prefs.kt, app/src/main/java/app/olaunchercf/ui/AppDrawerAdapter.kt, app/src/main/java/app/olaunchercf/ui/SettingsFragment.kt, app/src/main/res/values/strings.xml
Hope this is ok having the setting in the Extra category all on its own if not feel free to move it or other settings to that category.
=> feat: add toggle for "open apps automatically"

.github/workflows/release.yml
[Example](https://github.com/HeCodes2Much/mLauncher/releases/tag/1.2.1)
Not too sure how to get `secrets.SIGNING_KEY` on windows or mac but below is Linux
```
openssl base64 < foo.jks | tr -d '\n' > foo.jks.txt
```
=> fix: build singed apk

app/src/main/java/app/olaunchercf/ui/SettingsFragment.kt
Fixed appDoubleTap label...
Not really worth a PR but i cant be bothered to only open a issue for something so small when i can fix it.
=> fix: double tap app name

fastlane/metadata/android/en-US/full_description.txt
Added "Arabic" to the list of languages in the F-droid description page
=> Added "Arabic" to the list
